### PR TITLE
Cocoa: Add drag and drop support

### PR DESCRIPTION
**Pull request by dwhinham**
This fixes issue #19.

### CODE REVIEW

**Comment by dwhinham** [comment]
My cocoa branch is now a clone of your cherry-picked cocoa, so GitHub auto-merge should work :smiley:

**Comment by Deltafire** [comment]
Nice work!

After scrutinising the border, I've now noticed a 1 pixel gap at the right of the top instrument/sample panel - probably been there since day 1.

**Comment by dwhinham** [comment]
Thanks! :smile:

A gap - that's strange! It's not just the bevel shadow thing?

**Comment by Deltafire** [comment]
I think it probably is the edge of the bevel.

**Pull request merged**
