### PR TITLE
Sample editor offset feature

### PR DESCRIPTION
**Pull request by dwhinham**

### CODE REVIEW

**Comment by Deltafire** [comment]
I'm thinking that this feature is a bit hidden and users may not realise it's there - the problem is people don't read the documentation.  Perhaps it should display the offset all the time, not requiring ctrl/cmd to be held - or maybe a hint "Hold ctrl/cmd for offset".

**Comment by Deltafire** [comment]
Heh, just noticed that holding shift enables drawing.

**Comment by dwhinham** [comment]
I actually did the CTRL/Cmd thing *because* it seemed to complement the Shift for drawing. :smiley:
I thought it'd be a bit distracting and get in the way when setting loops or ranges etc if it was permanently on, as this is a tool you're probably only going to use occasionally.

I reckon we should just make a big deal about it in the next release notes and documentation. Or we could do a first-usage dialog with "What's new", or the hint you suggested.

**Comment by Deltafire** [comment]
I was trying to think of a way where the UI would be usable without having to read any sort of documentation, but I can’t think of an easy way to do this - maybe we could squeeze in some text in the sample editor “Shift = draw, CTRL/CMD = find offset”, but that will probably look ugly.  Some apps have a “Did you know?” dialog with tips at startup which could work.  I think we’ll just mention it in the docs and in the changelog for now.

Software like Photoshop is full of hidden features, even more hidden than this!

**Pull request closed without merging**
